### ISSUE TITLE
Permettre l'utilisation de `dict` dans les extras

### ISSUE THREAD

**Issue by streino** [opendatateam/udata-front-kit#103]
D'après ce que j'ai compris, il est possible d'utiliser des `dict` dans les extras en contournant la validation, qui ne s'applique qu'au premier niveau d'une propriété `extras`. Les `dict` fonctionnent donc, mais ont été exclus pour une raison que je ne connais pas.

```
# invalid
params.extras['foo'] = {}

# unintentionally? valid
params.extras['foo'] = [{}]
```

Serait-il possible d'assouplir cette validation pour permettre l'utilisation de `dict` même en premier niveau ? Par exemple, sur Ecosphères, cela nous permettrait d'associer des extras _par dataset_ dans un topic, en utilisant l'id du dataset en clé du `dict`.

```
params.extras['properties'] = {
  'dataset_id1': {
    'label': ...,
    'usage': ...
  },
  'dataset_id2': {
    ...
  }, ...
}
```

**Comment by maudetes** [comment]
Côté data.gouv.fr, en effet les extras n'avaient pas été pensés pour y mettre du contenu nested via des `dict` à l'origine.

Etant donné que ça répond à des besoins qu'il n'est pas possible d'exprimer autrement, vous pouvez largement utiliser les `dict` ainsi, et on va regarder prochain sprint pour autoriser les `dict` au premier niveau si c'est simple côté back.

En l'absence de validation spécifique, il n'est pas forcément recommandé de trop pousser dans cette direction s'il est envisageable de faire le travail sur les métadonnées du modèle directement.
Typiquement, rajouter des métadonnées sur un dataset dans le contexte d'un topic me paraît pertinent au-delà du contexte d'écosphère. Mais comme des développements éventuels prendraient du temps, c'est plus pour que vous ayez en perspective.

**Comment by maudetes** [comment]
C'est déployé en prod, vous pouvez maintenant mettre un `dict` au premier niveau d'un extra :)
