### ISSUE TITLE
feat(social): lister commentaires d'un bouquet

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#113]
Depends on #112 
Depends on #200
Relates to #128 

### Job story

Utilisateur : Agent, réutilisateur/trice associatif, lobbyst.

Lorsque je dois rédiger un rapport avec un indicateur, 
je veux pouvoir trouver les bonnes données à utiliser pour le produire,
afin de mieux remplir ma mission de service public.

### Contexte

Lorsque je cherche un bouquet de données,
Et que j'en trouve un mais que je ne suis pas sûr si c'est celui que je veux,
je m'attends à pouvoir lire les commentaires d'autres usagers pour me faire une idée.

### Problème

À présent, je ne peux lire les commentaires associés à un bouquet

### Proposition de solution au problème

Dans la page d'un bouquet,
Je vois un encadré « Discussions »,
Où je peu lire les commentaires laissés par d'autres usagers.

(Reprendre le composant déjà utilisé pour les datasets):

![Image](https://github.com/ecolabdata/ecospheres-front/assets/329236/f1793a72-f8b6-4df2-a2fd-8c8db2ab4803)

### Éléments supplémentaires de ma proposition

- Quand il n'y pas encore de commentaire, je vois un message « Soyez prémièr(e) à démarrer une discussion sur ce bouquet ! » avec un lien/bouton « Démarrer la première discussion ».

### Définition de terminé

- [ ] L'utilisateur peut voir les commentaires d'un bouquet
- [ ] S'il y en a pas, l'utilisateur peut créer la première discussion du bouquet

### Critères d'acceptation

- [ ] Une application de prévisualisation déployée où tester cette fonctionnalité
- [ ] Une batterie des tests unitaires et d'intégration déployés automatiquement
- [ ] Du linting et du formatage du code vérifiés automatiquement

**Comment by streino** [comment]
Quelle différence avec https://github.com/ecolabdata/ecospheres-front/issues/128 ?

**Comment by bonjourmauko** [comment]
@streino Ce ticket correspond au rendu des discussions d'un bouquet, quand #128 fait référence au fait même de commenter.

En général, les issues sont là pour décrire des situations d'un point de vue de l'utilisateur, et sont donc agnistiques en termes d'implementation.

S'il s'avère qu'une pull request addresse les deux, génial ! Mais ils restent deux tickets séparés qui décrivent une solution s'addressant à deux utilisateurs différents.

**Comment by streino** [comment]
Ma question ne porte par sur l'implémentation, mais sur l'expression claire du besoin et les dépendances. "Discuter autour d'un bouquet" (128) nécessite de visualiser ET commenter une discussion, donc englobe ce ticket (113). Si 128 ne couvre que la partie "commenter", le titre du ticket devrait refléter ça. Et 128 devrait dépendre de 113 puisqu'un utilisateur ne va pas commenter dans le vide.

**Comment by bonjourmauko** [comment]
> Ma question ne porte par sur l'implémentation, mais sur l'expression claire du besoin et les dépendances.

> "Discuter autour d'un bouquet" (128) nécessite de visualiser ET commenter une discussion, donc englobe ce ticket (113).

> Si 128 ne couvre que la partie "commenter", le titre du ticket devrait refléter ça.

Descriptions modifiées.

> Et 128 devrait dépendre de 113 puisqu'un utilisateur ne va pas commenter dans le vide.

Fait !

**Comment by bonjourmauko** [comment]
@streino description mise à jour.
