### ISSUE TITLE
feat(edit): éditer un bouquet publié

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#125]
Depends on ecolabdata/udata-front-kit#80 
Depends on ecolabdata/udata-front-kit#112 
Depends on ecolabdata/ecospheres#87

### Contexte

Pouvoir éditer un bouquet à partir d'une liste consultable (espace admin, espace membre).

L'édition à partir de la visualisation (`DetailView`) est comprise dans ecolabdata/udata-front-kit#225

**Comment by streino** [comment]
On reprendra ce point lorsqu'on s'attaquera à la page "admin" des bouquets.
