### ISSUE TITLE
feat(social): commenter un bouquet

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#128]
Depends on #112
Depends on #199 
Relates to #113

### Job story

Utilisateur : Agent, réutilisateur/trice associatif, lobbyst.

Lorsque je dois rédiger un rapport avec un indicateur, 
je veux pouvoir trouver les bonnes données à utiliser pour le produire,
afin de mieux remplir ma mission de service public.

### Contexte ou situation

Lorsque je cherche un bouquet de données,
Et que j'en trouve un mais que je ne suis pas sûr si c'est celui que je veux,
je m'attends à pouvoir écrire un commentaire pour qu'on clarifie le cas d'utilisation.

### Problème rencontré par les utilisateurs

À présent, je ne peux pas commenter sur un bouquet.

### Proposition de solution au problème

Dans la page d'un bouquet,
Je vois un encadré pour laisser un commentaire,
J'écris donc « À quoi ça sert de bouquet »,
Je fais clique sur « Commenter »,
Je vois que mon commentaire est maintenant visible sur la page du bouquet,

(Deux semaines après - hors scope de cette issue)

Je reçois un email d'Écosphères,
Avec une notifiation de la créatrice du bouquet,
Avec le message : « Monsieur, ce bouquet est utile pour votre cas d'usage ». => ce message est aussi visible par l'ensemble des utilisateurs sur Ecosphères

_Ajoutez une image ici si vous en avez une_. @martyKN

### Éléments supplémentaires de ma proposition

- Si je ne mets rien, c'est clair que je ne peux pas envoyer le commentaire.
- Je ne peux pas éditer le commentaire, mais je vois un message m'indiquant de prendre contact avec l'équipe en cas de faute de frappe.

### Définition de terminé

- [ ] L'utilisateur peut commenter un bouquet

### Critères d'acceptation

- [ ] Une application de prévisualisation déployée où tester cette fonctionnalité
- [ ] Une batterie des tests unitaires et d'intégration déployés automatiquement
- [ ] Du linting et du formatage du code vérifiés automatiquement

**Comment by bonjourmauko** [comment]
Je t'assigne @streino comme vu en planif pour investigation de faisabilité.

**Comment by streino** [comment]
Pas encore géré côté data.gouv, mais c'était sans compter la réactivité foudroyante de @maudetes 🙏 
https://github.com/opendatateam/udata/pull/2922

Une fois la PR mergée et déployée sur demo, ça sera : 
```
POST /api/1/discussions/
{
  "comment": "un commentaire",
  "subject": {
    "class": "Topic",
    "id": "53541d16c751df3488825af7"
  },
  "title": "Une discussion sur Topic"
}
```

**Comment by streino** [comment]
Exemple de _jeu de données_ avec discussion : https://ecospheres.netlify.app/datasets/repertoire-des-logements-locatifs-des-bailleurs-sociaux
On peut reprendre ça pour les bouquets. A voir si on garde l'accordéon tel quel @martyKN ?

**Comment by streino** [comment]
Composant discussion de data.gouv : https://github.com/etalab/udata-front/tree/master/udata_front/theme/gouvfr/assets/js/components/discussions
Ils parlent d'extraire ces composants à terme dans une lib. Ça peut être intéressant de le reprendre tel quel (ou avec modifs minimales si besoin) et switcher sur la lib lorsqu'ils la sortiront.

**Comment by bonjourmauko** [comment]
> Composant discussion de data.gouv : https://github.com/etalab/udata-front/tree/master/udata_front/theme/gouvfr/assets/js/components/discussions Ils parlent d'extraire ces composants à terme dans une lib. Ça peut être intéressant de le reprendre tel quel (ou avec modifs minimales si besoin) et switcher sur la lib lorsqu'ils la sortiront.

@martyKN

**Comment by streino** [comment]
CC @geoffreyaldebert pour info

**Comment by martyKN** [comment]
en reprenant le modèle dgfr on arrive la dessus 
![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/29111366-8d36-49a4-abd2-b5f2a18a7153)

![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/8285bae7-24f5-4836-a00e-e143d7e48525)

j'ai fait une section "discussions dans "V1 Composants" c'est fait avec des screenshots provenant de dgfr https://www.figma.com/file/YmsbJVui0zKVAHNx9NPFAA/Bouquets?type=design&node-id=2669%3A83308&mode=design&t=1UARepYLJdT208eB-1

**Comment by bonjourmauko** [comment]
> @streino : (...) Pour moi dans tous les cas on a visualiser -> commenter. Même lorsque la discussion n'existe pas encore il faut la visualiser.

> @bonjourmauko : (...) Il me semble plus cohérent de commencer par la visualisation. (...) Je vous laisse voir avec @edelagnier ce qui vous semble plus pratique côté implémentation.

Via @bonjourmauko in https://github.com/ecolabdata/ecospheres-front/issues/180#issuecomment-1825767294 (redacted for brevity).

**Comment by abulte** [comment]
Done
