### ISSUE TITLE
produit(impact): définition et suivi de métrique d'impact de premier ordre

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#136]
Depends on #135 

À différence de #135, celle-ci est la _vraie métrique qu'importe_.

Cf : https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-gere-mon-produit-et-son-impact

**Comment by streino** [comment]
Suivi par Martin
