### ISSUE TITLE
feat(nav): montrer un message quand une recherche de bouquet ne donne pas de résultat

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#164]
Depends on #112 
Depends on #116 

#### Naviguer les bouquets

Utilisateur: agent / consommateur de données

Lorsque je dois rédiger un rapport,
je veux savoir quels sont les indicateurs pertinents pour le sujet du rapport,
afin de mieux remplir ma mission de service public.

#### Rechercher (trouver) un bouquet

Utilisateur: agent / consommateur de données

Lorsque je dois rédiger un rapport avec un indicateur,
je veux savoir si les données pertinentes existent,
afin de remplir encore mieux ma mission de service public.

### Contexte ou situation

Lorsque je navigue les bouquets par thématique et par chantier,
Et qu'il n'y a pas de bouquets pour mes critères,
Je m'attends à avoir un message explicatif avec un call-to-action:

- Qui me rassure que je ne me suis pas trompé
- Qui me rassure que le site marche bien
- Qui me donne d'idées sur que faire

### Problème rencontré par les utilisateurs

Pour l'instant, il n'y a rien :

<img width="1208" alt="Screenshot 2023-11-16 at 14 06 32" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/cfc37450-52fe-4b0a-87dd-571cc5cee0f8">

### Proposition de solution au problème

Je vois un message comme celui ci infra :

![pasted image 0](https://github.com/ecolabdata/ecospheres-front/assets/329236/cb9c6356-0957-4411-bffe-a32b175acef5)

**Comment by abulte** [comment]
Si j'ai bien compris, done

<img width="1298" alt="Capture d’écran 2023-12-20 à 12 38 23" src="https://github.com/opendatateam/udata-front-kit/assets/119625/5d8da60d-91c8-4a40-baf7-ffa62aac30ba">
