### ISSUE TITLE
Harmoniser les types des composants (composition)

### ISSUE THREAD

**Issue by abulte** [opendatateam/udata-front-kit#178]
Historiquement, les composants d'Ecosphères sont écrits sous forme de [`<script setup>`](https://vuejs.org/api/sfc-script-setup.html), par exemple [la Home](https://github.com/ecolabdata/ecospheres-front/blob/67739f34d2a14f344573ed194f6f6b852a0abc69/src/views/HomeView.vue#L1).

Cependant, des composants n'utilisant pas cette syntaxe ont été introduits, par exemple [HomeThemes](https://github.com/ecolabdata/ecospheres-front/blob/67739f34d2a14f344573ed194f6f6b852a0abc69/src/components/HomeThemes.vue#L31).

Il serait bon d'utiliser le même type de composants partout. Vu la doc ci-dessus, plutôt `<script setup>` :

> It is the recommended syntax if you are using both SFCs and Composition API.

**Comment by bonjourmauko** [comment]
Y a-t-il une différence ou une préférence pour une syntaxe ou l'autre ? Cela m'a effectivement confondu pas mal.

**Comment by bonjourmauko** [comment]
Je vois que cette diversité va au-delà des composants, par exemple les [stores](https://github.com/ecolabdata/ecospheres-front/blob/main/src/store/DatasetStore.js#L21) semblent aussi ne pas (encore?) utiliser la _composition API_.

Il me semble qu'il est découragé avec TypeScript d'utiliser trop `this` : argument favorable à utiliser la _composition API_ partout ?

Dans tous les cas, +1 à en choisir une seule syntaxe.

**Comment by abulte** [comment]
Pour les stores c'est [possible de faire un truc qui ressemble](https://pinia.vuejs.org/introduction.html#basic-example:~:text=You%20can%20even%20use%20a%20function%20(similar%20to%20a%20component%20setup())%20to%20define%20a%20Store%20for%20more%20advanced%20use%20cases%3A) mais je ne l'ai jamais vu utilisé dans la vraie vie, je ne pense pas que ça vaille le coup.

Pour les composants, de ce que je vois dans l'écosystème Vue et même dans la doc (cf ci-dessus), l'état de l'art / le futur proche c'est composition API + script setup. Ca ne marchait pas complètement avec TS jusqu'à la version 3.1 (qui a 2 ans) mais maintenant ça semble être the way to go.

**Comment by abulte** [comment]
Il en reste deux 😢 

- `BouquetContentFieldGroup.vue`
- `BouquetPropertiesFieldGroup.vue`
