### ISSUE TITLE
Gérer les états "brouillon" et "publié" d'un bouquet

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#179]
Depends on ecolabdata/udata-front-kit#85 
Depends on ecolabdata/udata-front-kit#86
Depends on ecolabdata/udata-front-kit#160
Depended upon by ecolabdata/ecospheres#90 

#### Créer un bouquet

Utilisateur: agent / producteur de données

Quand je veux partager les données nécessaires pour réaliser des indicateurs,
Je veux pouvoir maintenir un même catalogue au même endroit,
Pour que d'autres puissent s'en servir et l'améliorer.

### Contexte ou situation

Quand je commence la création d'un bouquet,
qu'il soit marqué comme « draft » (`private: true`).

Quand je finalise la création d'un bouquet (`Publier`),
qu'il soit marqué comme « publié » (`private: false`).

### Problème rencontré par les utilisateurs

Ce n'est pas le cas. On n'a pas moyen de distinguer un bouquet publié d'un bouquet bruillon.

### Proposition de solution au problème

Je commence la création d'un bouquet,
Et je vois le texte « Pas encore publié ».

Quand je clique sur « Publier »,
Je vois le texte (dans n'importe quelle page concernant ce dossier) « Publié ».

### Éléments supplémentaires de ma proposition

- Quand je vois la liste de bouquets (soit par recherche ou par navigation), je ne vois pas de bouquets qui n'ont pas encore été publiés.

### Définition de fini

- [ ] L'utilisateur créateur de bouquets doit « voir » quand son bouquet a été publié
- [ ] L'utilisateur consommateur ne doit voir que les bouquet qui ont été publiés.
- [ ] Une application de prévisualisation déployée où tester cette fonctionnalité
- [ ] Du linting et du formatage du code vérifiés automatiquement

**Comment by martyKN** [comment]
pour la partie "publié" y'a un bouton "publier" sur le dernier sceen de "creation de bouquet" et pour la partie draft j'ai quelques questions sur les fiasabilités techniques avant de me lancer.

**Comment by bonjourmauko** [comment]
Bonnes questions !

>     * [ ]  si je quitte la page, ca l'enregistre ? où que je sois dans l'étape de création

Oui ! C'est déjà le cas : chaque fois que tu passes d'une étape à l'autre (dans la création du bouquet), les changement sont enrégistrés ipso facto.

(C'est une optimisation qu'on a fait dès le départ pour simplifier aussi bien l'implem que la UX).

>     * [ ]  où est ce que je pourrais retrouver mon draft par la suite? (techniquement parlant) partout?

Pour le moment, il me semble que tous les topics sont marqués comme publiés. Donc tu peux les voir sur Écosphères et sur datagouv.

Si l'on introduit la notion de « draft » :

- Tu peux toujours retrouver les bouquets pas encore publiés sur datagouv.
- Il n'existe pas encore d'espace pour les re-voir sur Écosphères (sauf si tu as noté le `slug`)
  - Pour info : quand tu crées un bouquet, celui-ci est associé à toi (ton compte).

>     * [ ]  est ce que le type d'auth dgfr qu'on utilise suffirait à garder des bouquet en draft ?

Je ne sais pas poke @abulte : peut bien utiliser l'attribut « private » n'est-ce pas ?

>     * [ ]  ca veut dire qu'il faut qu'on s'attaque d'abord aux compte utilisateurs nan? => et que en gros un user peut depuis une interface admin visualiser l'ensemble des bouquets sur lesquels il a collaboré ceux qui sont publiés et ceux qui sont en draft.

Oui ! Le premier scénario est déjà possible d'ailleurs :) (tout bouquet que tu crées est associé à ton compte).

> En gros est ce qu'il y a pas d'autres tickets avant de pouvoir s'attaquer à celui la?

AMHA je pense que ce ticket est plutôt un prérequis pour les autres.

Pour info :

- https://github.com/ecolabdata/ecospheres-front/issues/126
- https://github.com/ecolabdata/ecospheres-front/issues/181
- https://github.com/ecolabdata/ecospheres-front/issues/125
- https://github.com/ecolabdata/ecospheres-front/issues/182

**Comment by abulte** [comment]
> Je ne sais pas poke @abulte : peut bien utiliser l'attribut « private » n'est-ce pas ?

On pourrait utiliser "private" pour modéliser ça en effet. De ce que je vois [du code actuel de udata](https://github.com/opendatateam/udata/blob/49308cfc34452c6993624fcda1f3c24bcb937926/udata/core/topic/apiv2.py#L87), il n'y a pas de contrôle sur cet attribut sur la liste des topics, donc on récupérerait tous les topics quelque soit leur statut et il faudrait faire le tri côté front (ce qui casse des choses comme la pagination).

Si c'est important ça vaut peut-être le coup de voir ce qu'on peut faire évoluer côté data.gouv.fr : soit ajouter un filtre private|notPrivate dans l'API, soit rendre le payload réactif en fonction de tes droits (private si tu as permission d'edit sur le jeu de données). @streino

**Comment by streino** [comment]
En effet on ne devrait afficher que les bouquets "publiés" par défaut.

Dans ce cas il faut voir comment on préfère récupérer les "brouillons" par l'UI : soit une page "admin" dédiée, soit un filtre dans la page bouquets, soit... ? @martyKN 

> Si c'est important ça vaut peut-être valoir le coup de voir ce qu'on peut faire évoluer côté data.gouv.fr : soit ajouter un filtre private|notPrivate dans l'API, soit rendre le payload réactif en fonction de tes droits (private si tu as permission d'edit sur le topic).

A mon avis les 2 peuvent être complémentaires. J'imagine qu'on pourra parfois vouloir afficher les deux types en même temps mais les distinguer visuellement.

**Comment by martyKN** [comment]
donc on lance la création d'une page admin pour la release de la V1?

**Comment by streino** [comment]
> En effet on ne devrait afficher que les bouquets "publiés" par défaut.

Après discussion avec @martyKN au tel, c'est pas forcément gênant d'avoir les "brouillons" pour la V1, y compris ceux des autres. Ça peut au contraire encourager les discussions/partages.

Dans ce cas, il serait utile de pouvoir distinguer "brouillon" et "publié", sans doute via un tag sur la tuile. On a l'info nécessaire dans le topic pour faire ça ?

> (@bonjourmauko) Il n'existe pas encore d'espace pour les re-voir sur Écosphères (sauf si tu as noté le slug)

Il me semble que même si on a noté le slug, si on filtre les brouillons et qu'ils ne sont pas dans le store, on pourra pas y accéder même avec son slug. @abulte tu confirmes ? 

Pour ce qui est d'une page admin dédiée, on peut lancer le design mais on ne prévoit pas de l'inclure en V1.

**Comment by abulte** [comment]
> Il me semble que même si on a noté le slug, si on filtre les brouillons et qu'ils ne sont pas dans le store, on pourra pas y accéder même avec son slug. @abulte tu confirmes ?

Non normalement les pages détails ne dépendent pas du load préalable du store. Sinon tu ne pourrais pas aller sur https://ecospheres.netlify.app/bouquets/pollution-de-leau sans passer par la page Bouquets. Si j'ai bien compris la question ?

**Comment by streino** [comment]
Tu as bien compris la question :) J'ai fait l'essai avec un topic meteo et ça ne s'affichait pas. J'ai mal interprété la cause : le problème du topic meteo est qu'il y a pas les bons extras.

Donc on peut bien accéder à un bouquet brouillon directement même si on a son slug/id ✅

**Comment by martyKN** [comment]
en recap soit

1. on ajoute un filtre qui permet au user propriétaire du bouquet de voir ses bouquets en draft et ses bouquets publiés. le filtre est ajouté sur a coté des autres filtres

2. on permet un tri global des bouquets trier par
a. bouquets brouillon
b. bouquets publiés
=>et on affiche en 1st les bouquets publiés puis à la suite les bouquets en brouillons

3. on créer l'interface admin

**Comment by bonjourmauko** [comment]
> Dans ce cas, il serait utile de pouvoir distinguer "brouillon" et "publié", sans doute via un tag sur la tuile. On a l'info nécessaire dans le topic pour faire ça ?

C'était prévu, mais ce n'est pas encore fait (ce pourquoi je créé ce ticket).

**Comment by abulte** [comment]
Une bonne partie est faite dans #321 — reste l'affichage des bouquets en mode brouillon. Pour l'instant on ne les affiche nul part (on peut y accéder uniquement via l'URL), notamment parce qu'il faudrait rendre la visualisation d'un bouquet résistante à un bouquet partiellement rempli (ou alors rediriger vers la vue d'édition, ça dépend qui peut les voir). Je mets un label discuss pour la suite.
