### ISSUE TITLE
feat(style): refacto page `datasets` 

### ISSUE THREAD

**Issue by geoffreyaldebert** [opendatateam/udata-front-kit#194]
##Demande de fonctionnalité

Se rapprocher au plus possible de la page Jeux de données de data.gouv.fr sur la page jeux de données de ecosphere-front

<img width="1243" alt="image" src="https://github.com/ecolabdata/ecospheres-front/assets/3721168/42765759-8098-4b76-8800-6846d94ea35f">

<img width="1243" alt="image" src="https://github.com/ecolabdata/ecospheres-front/assets/3721168/5e59879f-55e4-4cc4-9f46-7bff2811a645">

<img width="1243" alt="image" src="https://github.com/ecolabdata/ecospheres-front/assets/3721168/7564a51a-591f-4247-a7bd-3cf76a3068ba">

Liste des tâches à faire : 
- [x] #212
- [x] #213
- [x] #214
- [x] #215
- [x] #216
- [x] #217
- [x] #218
- [x] #219
- [x] #220
- [x] #221
- [x] Pour le moment, ne pas s'embêter avec les boutons "Mettre en avant", "Ajouter aux favoris", "Modifier", 

Cc @agarrone  @streino

**Comment by geoffreyaldebert** [comment]
@agarrone si tu veux mettre un visuel de cette viz intermédiaire que l'on pourrait mettre aux discussions

**Comment by streino** [comment]
L'onglet "Informations" est également prévu ?

**Comment by streino** [comment]
> L'onglet "Informations" est également prévu ?

Yep: https://github.com/opendatateam/udata-front-kit/pull/328
