### ISSUE TITLE
feat(style): refacto page recherche datasets

### ISSUE THREAD

**Issue by geoffreyaldebert** [opendatateam/udata-front-kit#196]
## Demande de fonctionnalité

Se rapprocher du design ci-dessous pour la liste des Jeux de données lors d'une recherche :

<img width="919" alt="image" src="https://github.com/ecolabdata/ecospheres-front/assets/3721168/0a91c08f-7457-4304-8f74-93ea529b5be1">

A noter : 
- [ ] Fil d'ariane
- [ ] Les filtres avec les boutons bleus devront en fait être les thématiques (par exemple "Données climatiques de base" et "Données climatiques de référence pour le réchauffement climatique" pour meteo.data)
- [ ] carte jeux de données componentisés, packagés et utilisés dans le repo

Cc @agarrone @streino

**Comment by streino** [comment]
Il faut qu'on puisse configurer les filtres différemment pour chaque conf, y compris les désactiver.

**Comment by streino** [comment]
@Jorek57 @geoffreyaldebert on est bon sur ce ticket ?
