### ISSUE TITLE
Augementer la taille du champ "objectif du bouquet" dans l'etape 1 de création de bouquet

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#229]
On attend des utilisateur.rices qu'iels soient le plus exhaustif possible sur les objectifs d'un bouquet (etape 1 sur 4 de la création de bouquet) 
Aujourd'hui le champ est assez réduit et n'invite pas à mettre beaucoup de contenu meme si le champ est agrandissable à la main. Est il possible de mettre un champ plus important ?
![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/f622914a-d6c1-4543-9b29-19b8d2e279c5)

**Comment by streino** [comment]
@martyKN la box a été agrandie. Ca te convient ?

**Comment by martyKN** [comment]
yes ! pour le moment, a voir à l'usage avec nos usagers :)
