### ISSUE TITLE
Pb de navigation fil d'ariane

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#239]
Une incohérence d'UX apparait quand je suis sur une page chantier (screenshot) ![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/699b5ff7-917c-412e-b1e4-b372786e0373)

et que je veux revenir en arrière via le fil d'ariane

![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/1c8eecd7-c878-43f1-968b-118eec318e55)

je reviens à une page avec l'ensemble des données dans la thématique. Je trouve que ce n'est pas intuitif, d'autant plus que si je suis dans **chantiers transvers** > **données environnementale** et que je fias la meme opération, la page reste la meme alors que mon souhait etait de revenir une etape avant via le fil d'ariane
Il me semble qu'on en avait parlé, mais l'expérience me semble très bizarre.

**Comment by streino** [comment]
@martyKN peux-tu retester ? J'ai l'impression que le breadcrumb se comporte correctement, mais je ne suis pas certain d'avoir bien compris le problème que tu décris.

**Comment by martyKN** [comment]
@streino cela a surement été corrigé. dans mes screen, le breadcrumb a une incohérence : 
quand `chantiers transverses` est souligné je devrais voir les bouquets qui sont dans ce chantier. Hors `pollution de l'eau` n'est pas dans ce chantier. Mais c'est fix maintenant donc je pense qu'on peut close
