### ISSUE TITLE
Switcher sur le composant DsfrFooter

### ISSUE THREAD

**Issue by streino** [opendatateam/udata-front-kit#275]
@abulte sur https://github.com/ecolabdata/ecospheres-front/pull/269 :

> Je remarque qu'on est de plus en plus proche du composant DsfrFooter de [vue-dsfr](https://github.com/dnum-mi/vue-dsfr/tree/main), il ne doit pas manquer grand chose pour pouvoir utiliser leur composant directement. Les gestions des liens externes si j'ai bien suivi https://github.com/ecolabdata/ecospheres-front/pull/247. Il faut qu'on se note quelque part d'ouvrir une issue chez eux et de switcher vers leur composant je pense @streino.

Dont acte. 
- [x] Confirmer diff footer custom vs DsfrFooter
- [x] Créer ticket chez https://github.com/dnum-mi/vue-dsfr 
- [x] Switch custom footer -> DsfrFooter

**Comment by abulte** [comment]
https://github.com/dnum-mi/vue-dsfr/pull/678 (FYI @maudetes)
