### ISSUE TITLE
pb d'affichage dans "création de bouquets"

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#282]
le bouton radio déborde sur le search. Ou plutot le search déborde sur le bouton radio 
![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/b204e1aa-89ff-4708-b3df-9f7a377b7091)

**Comment by streino** [comment]
La barre de recherche est maintenant en dessous du groupe de radioboxes.
