### ISSUE TITLE
pb d'affichage sur le recap du bouquet

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#284]
quand je suis à l'etape récapitulatif du bouquet, il y a un pb d'affichage au niveau de l'accordéon des données. Il est décrit comme fermé, les lignes sont extrêmement larges
![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/c0343b71-ea42-4df2-8a8f-16df6bb9428c)

**Comment by streino** [comment]
Étrange, je n'arrive pas à reproduire. Tu as fait la création d'une traite sans modifications ? Ou tu as fait d'autres manips intermédiaires (genre ajouter puis supprimer un jeu de données, revenir en arrière, etc.)

**Comment by martyKN** [comment]
la création d'une traite et ca me l'a refait sur le dernier bouquet que j'ai crée

**Comment by martyKN** [comment]
j'ai pas réussi à reproduire le bug. je propose qu'on laisse ouvert pour le moment. Je relance ici en décrivant mieux si le bug se reproduit.

**Comment by streino** [comment]
@martyKN des news ?

**Comment by martyKN** [comment]
ca reproduit pas (pour le moment :))

**Comment by streino** [comment]
Je ferme, si jamais tu reproduits plus tard, tu pourras réouvrir le ticket
