### ISSUE TITLE
Ajout invalide d'une donnée à un bouquet alors que tous les champs obligatoires n'ont pas été remplis

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#285]
Quand je complète les données dans la phase 3 de création de bouquet =>
Si je ne met pas de texte dans la description mais que je met un titre et un lien URL, et que je clique sur "ajouter la donnée" la donnée ne s'ajoute pas car
> je n'ai pas mis de description
>mais mon lien url + mon titre ont disparu.
> je ne remarque pas forcement que la donnée ne s'est pas ajoutée

Il faudrait désactiver le bouton "ajouter la donnée" tant que le texte de la description ou le titre de la donnée n'est pas complété
![image](https://github.com/ecolabdata/ecospheres-front/assets/74351881/5a7dca65-c8fd-437f-8d37-71b7e6a091d2)

**Comment by streino** [comment]
On a notre première régression 🥳
Ça avait été implémenté et testé. On va attendre de merger https://github.com/ecolabdata/ecospheres-front/pull/223 avant de regarder, c'est peut-être déjà corrigé dans cette branche ? @edelagnier

**Comment by edelagnier** [comment]
il y a des tests pour valider avant de pouvoir changer d'étape et de soumettre donc je dirai oui.
Pour confirmer, les critéres que j'applique sont : 
etape 1 : champs nom et description rempli
etape 2 : champs theme et sous-theme rempli
etape 3 : liste des datasets non vide
