### ISSUE TITLE
Uniformiser la gestion de markdown

### ISSUE THREAD

**Issue by edelagnier** [opendatateam/udata-front-kit#297]
Actuellement, le code utilse soit Markdown-it (cf SimplePageView, HomeView) soit Marked (via utils/index.js).

**Comment by edelagnier** [comment]
suggestion : créer un composant MarkdownField qui incluerait : 
- un champ, 
- une mention avec un lien vers une présentation de la  syntaxe markdown (voir exemple sur creation bouquet)
- affichage optionel d'une preview (activable ou non par l'utilisateur)

**Comment by abulte** [comment]
Voir si https://tsdocs.dev/docs/@etalab/data.gouv.fr-components/1.11.9/functions/markdown.html#markdown peut-être utile
