### ISSUE TITLE
Markdown dans les discussions

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#300]
Est ce qu'on enlèverai pas le markdown dans les discussions.
Ca risque de faire rapidement pas propre si les gens l'utilise.
ou bien, peut on choisir d'exclure certain attribut du markdown? je pense aux différentes taille de titres
![image](https://github.com/opendatateam/udata-front-kit/assets/74351881/a41e00ef-d911-4e83-82e4-997ab66d0cdf)

**Comment by abulte** [comment]
Oui, d'autant que data.gouv.fr ne parse pas le markdown dans les discussions, après vérification.
