### ISSUE TITLE
Pb au niveau des filtres thématique et affichage des bouquets dispo

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#316]
Problème de filtrage des bouquets lorque je recherche un bouquet via l'arborescence FNV.
-> quand je clique sur un chantier, par exemple "aménagement des villes", j'ai l'ensemble des bouquets présents dans Ecosphères. Je devrais n'avoir que les bouquets liés au chantier "aménagement des villes". 
Ce que je vois quand je clique sur "Aménagement des villes"
<img width="1347" alt="Capture d’écran 2024-01-08 à 16 46 10" src="https://github.com/opendatateam/udata-front-kit/assets/74351881/9d14b611-cbba-4ed1-bcbe-733d3113c5ca">

**Comment by abulte** [comment]
C'est réglé dans #315 tu peux tester sur https://deploy-preview-315--ecospheres.netlify.app/bouquets/?theme=Se%20loger&subtheme=Aménagements%20des%20villes
