### ISSUE TITLE
Pb de scroll lors de l'arrivée sur une nouvelle page

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#319]
Quand je suis sur l'ensemble des bouquets dans l'onglet Bouquets.
Je clique sur l'un des 4 bouquets complets (en dehors des drafts)
j'arrive tout en bas du bouquet, au niveau des discussions
-> je souhaiterais arriver en haut de la page du bouquet, et non en bas.

**Comment by martyKN** [comment]
c'est resolu j'ai l'impression

**Comment by abulte** [comment]
Le layout a dû changer depuis (moins de bouquets ?), mais le problème est toujours là. Par exemple : page jeux de données, scroller vers le bas, cliquer sur un jeu de données, se retrouver en bas de la page de détail.

J'élargis le titre, je rouvre et je fais un fix dans la foulée.
