### ISSUE TITLE
Description des données dans les bouquets

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#320]
dans les bouquets precedement crées, j'avais ajouté une description sur les données. 
Aujourd'hui ces descriptions ont disparues sur les 4 bouquets que j'ai crée
<img width="1132" alt="Capture d’écran 2024-01-08 à 18 30 13" src="https://github.com/opendatateam/udata-front-kit/assets/74351881/2c93a13d-5ce4-453f-8a3e-2ec81e27c8c9">

**Comment by abulte** [comment]
Comme pour #305, c'est à cause d'un changement du modèle de données dans #223.

A voir si une migration est pertinente (AMHA non), je mets un label discussion en attendant.

**Comment by abulte** [comment]
Obsolète suite au ménage sur les anciens bouquets 🤞
