### ISSUE TITLE
Impossibilité d'editer certains bouquets

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#334]
1 seul bouquet est à ce jour éditable : la plantabilité des arbres
Les autres (surchauffe urbaine, diag alimentaire, pollution de l'eau et diag artif) ne sont pas editables.
J'ai essayé avec différents compte (compte admin ecosphères, celui de Vincent & mon compte) et ca ne fonctionne toujours pas.

**Comment by abulte** [comment]
@martyKN c'est OK pour moi avec un compte admin (le mien ou celui d'Ecopshères). Par exemple j'ai bien "Editer le bouquet" sur "Suivi de la pollution de l'eau".

PI pour "Plantabilité des arbres" tu es owner du bouquet, donc pas besoin de compte admin pour l'éditer.

**Comment by martyKN** [comment]
Oh top, il y a du avoir une modif entre jeudi et maintenant car on a essayé avec Vincent et tous les comptes qu'on avait sous la main, dont le comtpe admin et ca ne fonctionnait pas. Mais maintenant, tout semble rentrer dans l'ordre

**Comment by abulte** [comment]
Bizarre, pas de modification sur le code du front depuis 🤔 Anyway si ça marche je ferme :-)

**Comment by martyKN** [comment]
en fait, il faut ré-ouvrir l'issue ! cela ne fonctionne toujours pas meme avec le compte admin. Pour le tester il faut cliquer sur editer le bouquet et faire une édition puis la valider et la on a bien une `Request failed with status code 400`

**Comment by martyKN** [comment]
https://github.com/opendatateam/udata-front-kit/assets/74351881/af05cd9c-66ca-4b99-8e6c-21928ed74d0e

**Comment by abulte** [comment]
Got it, rien à voir avec les droits en fait. Il y a des `id` internes pour les jdd externes qui sont posés par le front (mais sur Plantabilité, ça a changé depuis ou avant ?) et qui plantent le PUT :

```
[
  {
    "title": "Aires de captages",
    "description": "lorem ipsum",
    "uri": "https://www.data.gouv.fr/fr/datasets/aires-dalimentation-de-captages-france-entiere/",
    "id": "__internal__0",
    "available": "url available"
  },
  {
    "title": "Résultats du contrôle sanitaire de l'eau du robinet",
    "description": "lorem ipsum",
    "uri": "https://www.data.gouv.fr/fr/datasets/resultats-du-controle-sanitaire-de-leau-du-robinet/",
    "id": "__internal__1",
    "available": "url available"
  },
  {
    "title": "Forme et altitude de la surface du sol",
    "description": "lorem ipsum",
    "uri": "/datasets/61489f5ae64c7f138f1b2e15",
    "id": "61489f5ae64c7f138f1b2e15",
    "available": "available"
  },
  {
    "title": "Activités économiques productives",
    "description": "lorem ipsum",
    "uri": "/datasets/58a42c4088ee38635f9b81a4",
    "id": "58a42c4088ee38635f9b81a4",
    "available": "available"
  },
  {
    "title": "Code officiel géogrpahique",
    "description": "lorem ipsum",
    "uri": "/datasets/58c984b088ee386cdb1261f3",
    "id": "58c984b088ee386cdb1261f3",
    "available": "available"
  },
  {
    "title": "Masses d'eau souterraines",
    "description": "lorem ipsum",
    "uri": "/datasets/62f1776b1d176d391d3e86bb",
    "id": "62f1776b1d176d391d3e86bb",
    "available": "available"
  },
  {
    "title": "Découpage hydrographique",
    "description": "lorem ipsum",
    "uri": null,
    "id": "__internal__2",
    "available": "missing"
  }
]
```

**Comment by abulte** [comment]
> mais pas sur Plantabilité, ça a changé depuis ou avant ?

Je ne reproduis pas sur un nouveau bouquet, ça a donc dû changer avant. Maintenant on met des id `null`, ce qui me parait cohérent.

Also, `available` ne respecte pas le nouveau schéma non plus (`availability` maintenant). Voir aussi https://github.com/opendatateam/udata-front-kit/issues/320#issuecomment-1881602013.

**Comment by abulte** [comment]
Obsolète suite au ménage sur les anciens bouquets 🤞
