### ISSUE TITLE
Mise en forme de l'accordéon de données

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#336]
Quand on arrive sur un bouquet et qu'on va dans les `données utilisées` l'accordéon est déplié par défaut. Je suis d'avis qu'il soit replié par défaut.
Je sais qu'on a déjà eu cette discussion avec @streino qui est pour l'accordéon déplié, mais à l'usage, je trouve ca plus pertinent d'avoir une overview des données necessaires et ensuite rentrer dans le détail en dépliant petit à petit l'accordéon.
A discuter
<img width="1238" alt="Capture d’écran 2024-02-22 à 11 22 08" src="https://github.com/opendatateam/udata-front-kit/assets/74351881/100251d9-107c-4f6b-a17d-ac48df95911e">

**Comment by streino** [comment]
Avec de bons titres ça se tient en effet.
