### ISSUE TITLE
doc: add « Mentions légales » in footer

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#70]
## Demande de fonctionnalité

Quand j'utilise écosphères,
Je m'attends à ce les mentions légales soient présentes,
Pour m'assurer que ce site est conformité avec la législation en vigeur en France.

Par exemple, à minima :

- Editeurs
- Directeur de la publication
- Prestataire d’hébergement

https://doc.transport.data.gouv.fr/le-point-d-acces-national/generalites/mentions-legales-et-conditions-generales-dutilisation

**Comment by abulte** [comment]
Done avec des liens vers data.gouv.fr, ce qui me semble cohérent et suffisant pour ecologie.data.gouv.fr. A voir si besoin d'une page dédiée, n'hésite pas à rouvrir @streino.
