### ISSUE TITLE
doc: add CGU in footer

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#71]
## Demande de fonctionalité

Cf. #70 

Language required for limited liability of a beta service:

- Présentation du service
- Objet
- Qualité des informations publiées
- Vie privée
- Evolution et disponibilité du service

https://doc.transport.data.gouv.fr/le-point-d-acces-national/generalites/mentions-legales-et-conditions-generales-dutilisation

**Comment by abulte** [comment]
Cf https://github.com/opendatateam/udata-front-kit/issues/70#issuecomment-1864319592
