### ISSUE TITLE
ci: add a reverse proxy to handle beta.ecologie.data.fr

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#72]
## Amélioration technique

En vue du déploiement de « ecologie.data.fr », il est souhaitble de déployer « beta.ecologie.data.fr » (pour les raisons développées dans #74 et #73.

Pour ce faire, il est nécesaire de monter un proxy revers pour que les détails précis du déploiement (dans quel serveur, avec quel fournisseur, etc.) soient transparents pour l'usager.

**Comment by streino** [comment]
wont do
