### ISSUE TITLE
ci: deploy to beta.ecologie.data.gouv.fr

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#73]
Depends on #74 
Depends on #65 
Depends on #67 
Depends on #69 

## Amélioration technique

Dans l'esprit de garder l'agilité, surtout après une première « mise en prod », le contexte administratif impose de prendre en compte les particularités du cadre administratif et de la responsabilité envers les usagers (la relation entre les usagers et l'administration n'est pas une relation de type contractuelle mais une relation régie par le droit admnistratrif directement). Comme évoqué dans #74, il est **extrêmement** recommandé de faire un premier déploiement sur un sous-domaine _beta.ecologie.data.gouv.fr_ :

> 1. Protège l'équipe dans sa capacité à déployer de manière itérative et incrémentale ;
> 2. Améliore la communication et aligne les expectatives :
>   - Des sponsors qui savent que le site est en amélioration continue
>   - Du grand public qui sait qu'il peut y avoir des défauts car le site est toujours en construction
>   - Aux haut-fonctionnaires et juristes car explicite une souplese du service quant aux contraintes normales de tout service public qui n'est pas en bêta

**Comment by streino** [comment]
Probably not the (main) target: Most likely we'll be shooting for ecologie.data.gouv.fr.

Though there's the question of having *.ecologie.gouv.fr (or rather *.developpement-durable.gouv.fr) redirect.

**Comment by maukoquiroga** [comment]
It is, of course, up to you. I was thinking just in a `beta.*.ecologie.gouv.fr`, not for next year, but for next week.

**Comment by bonjourmauko** [comment]
> Ah ok. We might be able to deploy under data.developpement-durable.gouv.fr but we have to ask (and therefore plan) for it. Is there a need for this? In addition to netlify?

J'avais une coquille dans le domaine, je rajoute une description complète.

**Comment by streino** [comment]
A priori on part sur : 
- dev.ecologie.data.gouv: redirect sur ecospheres.netlify, avec les données de dev.data.gouv (en attendant d'y avoir accès on tape sur demo.data.gouv.
- demo.ecologie.data.gouv: "préprod" hébergée par data.gouv, avec les données de demo.data.gouv.
- ecologie.data.gouv: "prod" hébergée par data.gouv, avec les données de data.gouv.

Reste un point à confirmer avec la team data.gouv sur *.ecologie.data.gouv vs ecologie.*.data.gouv.

**Comment by bonjourmauko** [comment]
> A priori on part sur :
> 
>     * dev.ecologie.data.gouv: redirect sur ecospheres.netlify, avec les données de dev.data.gouv (en attendant d'y avoir accès on tape sur demo.data.gouv.
> 
>     * demo.ecologie.data.gouv: "préprod" hébergée par data.gouv, avec les données de demo.data.gouv.
> 
>     * ecologie.data.gouv: "prod" hébergée par data.gouv, avec les données de data.gouv.
> 
> 
> Reste un point à confirmer avec la team data.gouv sur _.ecologie.data.gouv vs ecologie._.data.gouv.

Yes ! Cela reste un point plus « bizdev » que technique : vous permettre d'avoir des vraies utilisateurs tout en vous protégeant. Je ne sais pas si « dev » c'est le meilleur nom mais de ce que tu décris cela remplit l'objectif de ce ticket.

**Comment by streino** [comment]
"dev" dans le sens dev informatique, pas "bizdev". A priori pas d'utilisateurs là dessus, ça sera le playground pour l'équipe tech Ecosphères. dev.data.gouv sert la même fonction.

A terme les utilisateurs seront uniquement sur ecologie.data.gouv (prod), et éventuellement demo.ecologie pour les plus téméraires.

Pour la release de décembre, on va devoir dévier un peu de cette cible.
Ce que je pressent c'est : 
- Release V1 sur demo.ecologie, potentiellement derrière un password.
- Page éditorialisée type "On arrive bientôt" sur ecologie.data.gouv, en attendant d'avoir tout le monde sur le pont en 2024 pour la release officielle.

**Comment by bonjourmauko** [comment]
> "dev" dans le sens dev informatique, pas "bizdev".

Oui, pardon. Ce que je voulais dire par « bizdev » c'est la casquette depuis laquelle je crée ce ticket.

>A priori pas d'utilisateurs là dessus, ça sera le playground pour l'équipe tech Ecosphères. dev.data.gouv sert la même fonction.

OK !

> A terme les utilisateurs seront uniquement sur ecologie.data.gouv (prod), et éventuellement demo.ecologie pour les plus téméraires.

Mauvaise approche AMHA cf. #74 etc.

> Pour la release de décembre, on va devoir dévier un peu de cette cible. Ce que je pressent c'est :
> 
>     * Release V1 sur demo.ecologie, potentiellement derrière un password.
> 
>     * Page éditorialisée type "On arrive bientôt" sur ecologie.data.gouv, en attendant d'avoir tout le monde sur le pont en 2024 pour la release officielle.

Et puis le big bang, sauf que ça ne marche pas (cf. https://apolitical.co/solution-articles/en/when-is-my-government-digital-service-ready-to-go-live). L'idée est d'avoir des métriques d'impact *avant* (#75) et qu'elles servent à guider le déploiement en continu. Si tu t'en prives, et que tu ne mesures l'impact qu'_ex post_, c'est déjà beaucoup trop tard. Je vous décourage vivement de suivre cette approche en cascade.

**Comment by bonjourmauko** [comment]
(Et le seul moyen d'avoir des métriques d'impact _avant_ l'annonce du ministre est d'avoir des vrais usagers dès plus tôt possible avec une version _beta_. C'est ça le sens de ce ticket).

**Comment by streino** [comment]
Je suis d'accord avec toi sur le principe, mais des contraintes internes ne nous permettent pas de d'ouvrir et communiquer en décembre.
