### ISSUE TITLE
feat: Add beta banner in header or nav linking to the CGUs

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#74]
Depends on #71 
Depends on #70 

## Demande de fonctionalité

L'ajoute d'un « banner » bêta rempli deux fonctions :

1. Protège l'équipe dans sa capacité à déployer de manière itérative et incrémentale ;
2. Améliore la communication et aligne les expectatives :
  - Des sponsors qui savent que le site est en amélioration continue
  - Du grand public qui sait qu'il peut y avoir des défauts car le site est toujours en construction
  - Aux haut-fonctionnaires et juristes car explicite une souplese du service quant aux contraintes normales de tout service public qui n'est pas en bêta 

### Sur la notion de bêta en général

<img width="794" alt="Screenshot 2023-11-23 at 17 56 03" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/6713d93e-7199-40ac-bf78-dcd2af8213dc">

https://doc.incubateur.net/communaute/travailler-a-beta-gouv/jutilise-les-outils-de-la-communaute/sous-domaine-beta-gouv-fr

### Sur l'aspect admionistratif et juridique

<img width="823" alt="Screenshot 2023-11-23 at 17 57 00" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/0e134246-ed47-4d4f-ad14-52331e424893">

https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/cadrer-juridiquement-son-produit/lexperimentation-difference-entre-le-sens-commun-et-la-definition-juridique

**Comment by abulte** [comment]
Done in header.
