### ISSUE TITLE
Mettre en place le tracking stats.data.gouv.fr

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#75]
Depends on ecolabdata/ecospheres#72 

## Amélioration technique

Le suivi est important pour mesurer ses métriques d'impact.

Sur les métriques d'impact : https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-gere-mon-produit-et-son-impact/definir-et-mesurer-limpact

Sur le cadre légale à respecter : (exemple) https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-securise-mon-produit/guide-rgpd-et-securite

**Comment by streino** [comment]
@geoffreyaldebert vous pourrez nous communiquer ici le code à inclure pour se brancher sur stats.data.gouv ? 🙏

**Comment by streino** [comment]
@geoffreyaldebert ok pour vous d'ici le 13 mars ?

**Comment by geoffreyaldebert** [comment]
yes on fait ça que sur le domaine principale ça vous va ? Je vous créé ça avec @jordanguedj

**Comment by streino** [comment]
Tu veux dire uniquement ecologie.data.gouv.fr (prod) et pas demo.ecologie ? Si oui, c'est tout à fait ok

**Comment by geoffreyaldebert** [comment]
yes et c'est done par Jo ✅

**Comment by streino** [comment]
Je rouvre pour tracker l'ajout dans la config ecosphères

**Comment by streino** [comment]
https://stats.data.gouv.fr/index.php?idSite=299
