### ISSUE TITLE
ci: add bouton « je donne mon avis » pour le suivi des métriques de satisfaction

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#76]
Depends on ecolabdata/ecospheres#72 

## Amélioration technique

Ensemble avec ecolabdata/udata-front-kit#75 , le bouton [« je donne mon avis »](https://observatoire.numerique.gouv.fr/) facilite la définition et le souvi des métriques d'impact [« proxy »](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-gere-mon-produit-et-son-impact/definir-et-mesurer-limpact/cauchemar-a-beta-la-mesure-dimpact), que sont les premières à mesurer par un produit à ce stade.

https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/je-gere-mon-produit-et-son-impact/definir-et-mesurer-limpact/comment-integrer-le-bouton

**Comment by streino** [comment]
Traité par https://github.com/ecolabdata/ecospheres/issues/94
