### ISSUE TITLE
ci: allow authentication using preview apps

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#77]
Depends on #72 

## Amélioration technique

Pour faciliter le test par des stakeholders non-techniques, il est important que les évolutions qui nécessitent d'une authentification puissent être testés avant d'un merge sur « main » (en vue de #73).

Note : je ne mets pas de dépendance ici car il y a de limitantes techniques importantes à considérer.

L'exemple est que l'on puisse s'authentifier quand on teste les previews :

<img width="1165" alt="Screenshot 2023-11-23 at 18 16 28" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/97c590aa-fcb5-42c7-8fbe-a70f6c290eb7">

**Comment by maukoquiroga** [comment]
Mmm... 🤔 with a reverse proxy? But already sounds awfully complicated.

**Comment by streino** [comment]
Ca fonctionne maintenant !
https://github.com/opendatateam/udata/pull/2935
