### ISSUE TITLE
Améliorer l'édition ponctuelle depuis le récapitulatif lors de la création d'un bouquet

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#80]
Depends on #79
Depends on #145 

#### Créer un bouquet

Utilisateur: agent / producteur de données

Quand je veux partager les données nécessaires pour réaliser des indicateurs,
Je veux pouvoir maintenir un même catalogue au même endroit,
Pour que d'autres puissent s'en servir et l'améliorer.

### Contexte ou situation

Lorsque je finalise la création d'un nouveau bouquet (#79),
Et que je me rend compte que j'ai mis n'importe quoi,
Je veut pouvoir modifier mes choix avant de publier le bouquet.

<img width="1267" alt="Screenshot 2023-11-24 at 07 29 02" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/74ced3f3-8efa-4da7-8ff4-f2735925a292">

### Problème rencontré par les utilisateurs

Je peux, mais ! (Il y a toujours un mais),
Quand je clique sur le stylo à droite de « Description du bouquet de données »,
J'arrive bien dans la page d'édition de cette étape,
Mais quand je clique « Suivant »,
J'arrive dans l'étape d'après au lieu de retourner vers le récapitulatif.

<img width="756" alt="Screenshot 2023-11-24 at 07 33 17" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/430af865-3000-4144-b5a8-a92779498729">

<img width="856" alt="Screenshot 2023-11-24 at 07 33 22" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/cb21dc97-fdbd-43bf-add8-95750671d4d7">

### Proposition de solution au problème

Quand je fais clique sur le stylo pour éditer la « Description du bouquet de données »,
Et que je fais des modifications,
Et que je fais clique sur « Suivant »,
Je m'attend à revenir directement au récapitulatif.

<img width="1267" alt="Screenshot 2023-11-24 at 07 29 02" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/b6698ece-9501-4248-883e-2e5a7d0f6ae8">

<img width="756" alt="Screenshot 2023-11-24 at 07 33 17" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/4cacc204-fd8b-4504-b84a-b533bfbdb828">

<img width="775" alt="Screenshot 2023-11-24 at 07 35 37" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/452e64b4-f5f4-461f-bebc-015e7f8df7fd">

### Définition de fini

- [ ] L'utilisateur peut revenir au récap après chaque édition
- [ ] Une application de prévisualisation déployée où tester cette fonctionnalité
- [ ] Des tests automatisés si jugé pertinent
- [ ] Des type hints à jour et testés automatiquement
- [ ] Du linting et du formatage du code vérifiés automatiquement

**Comment by maukoquiroga** [comment]
@martyKN Quelle est la liste de valeurs possibles ?

**Comment by bonjourmauko** [comment]
Vu en planif : attendre la suite de #145 et le temps restant.
