### ISSUE TITLE
feat(bouquet): créer un bouquet avec la réglementation en vigeur

### ISSUE THREAD

**Issue by bonjourmauko** [opendatateam/udata-front-kit#84]
Depends on #112

#### Créer un bouquet

Utilisateur: agent / producteur de données

Quand je veux partager les données nécessaires pour réaliser des indicateurs,
Je veux pouvoir maintenir un même catalogue au même endroit,
Pour que d'autres puissent s'en servir et l'améliorer.

### Contexte ou situation

Lorsque je crée un bouquet, je m'attends à pouvoir rajouter un ou plusieurs lois ou décrets associés.

### Problème rencontré par les utilisateurs

Ce n'est pas le cas.

### Proposition de solution au problème

> Je clique sur "Créer un nouveau bouquet"
> Et j'ai un message me disant de mettre les liens vers les lois et/ou décrets dans l'objet du bouquet.

TODO : maquette @martyKN 

![Visualiser un bouquet](https://github.com/ecolabdata/ecospheres-front/assets/329236/81026d42-e028-44ff-9175-6165eb4d6413)

### Définition de _done_

- Une application de prévisualisation déployée où tester ces changements

### OKR associé

TODO.

**Comment by streino** [comment]
Ca n'est pas prévu en v1. On prévoit de tout mettre dans le champ description avec la possibilité de markdown. Le découpage en sous-champs se fera une fois qu'on a des retours d'usagers.

**Comment by maukoquiroga** [comment]
Pour la v0.1.0 : dans la description

**Comment by streino** [comment]
Cleanup : La feature n'est pas prévue pour l'instant.
