### ISSUE TITLE
Ajouter un lien "Accessibilité : non-conforme" dans le footer

### ISSUE THREAD

**Issue by martyKN** [opendatateam/udata-front-kit#97]
### Job story

> User: toutes et tous.
>
> When we are getting ready to launch "Écosphères Beta",
> we want to be able to roll out each changeset continuously,
> so that we can get them into the hands of users as quickly as possible.

### Context or situation

Quand je visite Écosphères, et que l'accésibilité du site n'est pas conforme, je m'attends à être averti·e.

### Problem encountered by users

Ce n'est pas le cas.

### Proposal of how to solve the problem

> Quand je visite https://xxx.gouv.fr
> Et que je fais clique sur "Accessibilité : non-conforme" dans le footer
> Je vois une page similaire à https://api.gouv.fr/accessibilite

<img width="939" alt="Screenshot 2023-10-18 at 14 11 05" src="https://github.com/ecolabdata/ecospheres-front/assets/329236/a9d5e5ea-6721-4da0-a1d4-f48ccdf06df7">

### Additional elements of my proposal

- [Kit accessibilité](https://doc.incubateur.net/communaute/gerer-sa-startup-detat-ou-de-territoires-au-quotidien/construire-un-service-accessible-et-inclusif/accessibilite-et-rgaa/kit-accessibilite/investigation)

### Definition of done

- A deployed preview app where to test the aforesaid

### Related OKR

N/A.

**Comment by maukoquiroga** [comment]
Que faudrait-il pour le rendre conforme?

**Comment by maukoquiroga** [comment]
@martyKN pourrais-tu dès que tu auras un moment fournir à @martyKN le texte à ajouter sur cette page stp ?

**Comment by streino** [comment]
Traité par https://github.com/ecolabdata/ecospheres/issues/97
